name: clip
description: .
version: 1.0.1
homepage: https://github.com/hsul4n/dart-providers

environment:
  sdk: ">2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  photo_view: ^0.11.1
  image_picker: ^0.7.2+1
  media_saver: ^1.0.2
  flutter_image_compress: ^1.0.0-nullsafety
  flutter_cache_manager: ^3.0.0-nullsafety.1
  cached_network_image: ^3.0.0-nullsafety

dev_dependencies:
  test: ^1.5.1
