name: clip
description: .
version: 1.0.0
homepage: https://github.com/hsul4n/dart-providers

environment:
  sdk: ">2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # provider: ^4.1.3
  photo_view: ^0.9.2
  image_picker: ^0.6.7+4
  media_saver: ^1.0.2
  flutter_image_compress: ^0.7.0
  flutter_cache_manager: ^1.4.2

dev_dependencies:
  test: ^1.5.1
