name: clip
description: A simple, light image picker & builder widget.
version: 1.0.0
homepage: https://github.com/hsul4n/dart-clip

environment:
  sdk: ">2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  photo_view: ^0.9.2
  image_picker: ^0.6.7+4

dev_dependencies:
  test: ^1.5.1
